### PR TITLE
PancakeView implementation for WPF

### PR DESCRIPTION
**Pull request by yurkinh**
### Description of Change ###
PancakeView implementation for WPF.
Sample project for WPF.

### Platforms Affected ### 

- WPF

### Before/After Screenshots ### 

WPFPancakeView

### PR Checklist ###

- [x] Targets the correct branch

### CODE REVIEW

**Comment by sthewissen** [comment]
Awesome contribution! I will check this over the weekend and merge when done :) Thanks again!

**Comment by sthewissen** [comment]
Also, could you do an update of the README.md in this PR to update this section with what's supported for WPF? https://github.com/sthewissen/Xamarin.Forms.PancakeView#platform-support

**Comment by yurkinh** [comment]
Sure!. 
There should be the same functionality as for UWP. But I will check and update README.md file

**Comment by sthewissen** [comment]
The red border on the "THE FULL MONTY" sample doesn't look correct to me. Last I checked this does work on the UWP version and other samples on the page already use individually rounded corners. In theory it should be possible to make that work. Could you check that?

**Comment by yurkinh** [comment]
Sure. I will take a look at the weekend

**Comment by yurkinh** [comment]
@sthewissen  I have found ClipBorder control from MathApps package. It should solve issue with borders. But another issue has appeared

borders

**Comment by sthewissen** [comment]
That does look kind of strange, as if the content has shifted a few pixels to the left or the border is drawn with a horizontal offset 🤔

**Comment by yurkinh** [comment]
Yes. It solved one issue but has introduced another one. Not the perfect solution.
I also thought about using Border from WinUI that is currently used for UWP version (including shadows) but for WPF it will be available only from version WinUI 3.0.

**Comment by sthewissen** [comment]
We could possibly remove border support for WPF for now and introduce it at a later stage. That way most of the work you already did can be made available, and we can mark it as an unsupported feature for now on the README.

**Comment by yurkinh** [comment]
Sure. I totally agree with you.
I will update "readme" later today

**Comment by yurkinh** [comment]
I have disabled border functionality but left the code and updated readme.md

**Comment by yurkinh** [comment]
@sthewissen  Looks like merge has broken _readme.md_ structure
merge

**Comment by sthewissen** [comment]
Fixed :)

**Pull request merged**
