### PR TITLE
Support UWP and fix some small issues (take 2)

### PR DESCRIPTION
**Pull request by craigwi**
First cut to switch to FrameRenderer;
CornerRadius -> CornerRadii;
implement UWP PancakeViewRenderer;
fixed iOS border/clip mismatch using same path for both;
Implemented BackgroundColor for iOS;
much verification to do!

NOTE: integration into csproj files NOT done.

Addresses #10

### CODE REVIEW

**Comment by sthewissen** [comment]
Hey @craigwi - I'm fixing pretty much most of the current rendering issues that it has on a separate branch: https://github.com/sthewissen/Xamarin.Forms.PancakeView/tree/feature-improve-rendering

This has one small bug left in it before I would probably merge that into master. How would that play with your stuff? 🤔

**Comment by craigwi** [comment]
I'll check.

**Comment by craigwi** [comment]
The only substantial overlap in areas I changed with your recent changes was in the iOS renderer.  It looks like you addressed some if not all of the issues I did (albiet differently).  I'll move my changes forward when you integrate into master.

**Comment by sthewissen** [comment]
#49 Should introduce basic UWP support. Check the matrix on the README to see what isn't in yet.

**Pull request closed without merging**
